Add Labelled Images and more information about the User Interface
AY2223S1-CS2103T-T15-1/tp pull request #224
Opened 2022-10-30 07:04 UTC by prit3010

Added Labelled image and more details on the user interface

2022-10-30 09:11 UTC, prit3010 commented
Fixes #155

2022-10-31 07:07 UTC, chao890 approved these changes
approved

2022-10-31 07:23 UTC, Kok-je requested changes
Overall great work done. Minor edits that are easy to fix.

2022-10-31 07:23 UTC, Kok-je commented on docs/UserGuide.md
> +3. If you delete an employee that you are currently viewing, the next employee's details will be viewed.
Phrasing: the person info view will display the next employee's deatils

2022-10-31 07:23 UTC, Kok-je commented on docs/UserGuide.md
> +You can enter your user commands in the bottom section labeled as `Enter command here`.
Should add the three dots after the line to stay as accurate as possible to the actual application: `Enter command here...`

2022-10-31 07:55 UTC, Kok-je approved these changes
LGLM

2022-10-31 07:55 UTC, merged