Update batch-add clear exit ug
AY2223S1-CS2103T-T15-1/tp pull request #225
Opened 2022-10-30 09:10 UTC by prit3010

Updated batch-add, clear and exit in the User Guide

Now batch-add includes clear steps from creating CSV file to running the command

2022-10-30 09:14 UTC, prit3010 commented
Fixes #190

2022-10-31 07:12 UTC, chao890 requested changes

2022-10-31 07:12 UTC, chao890 commented on docs/UserGuide.md
> +| 8.    | Tags             | No               |
Please change table to follow master branch format

2022-10-31 07:12 UTC, chao890 commented on src/main/java/coydir/logic/commands/BatchAddCommand.java
> +                System.out.println(arg);
Pls remove

2022-10-31 07:29 UTC, Kok-je requested changes
LTGM

2022-10-31 07:29 UTC, Kok-je commented on src/main/java/coydir/logic/commands/BatchAddCommand.java
> +                System.out.println(arg);
This should be deleted

2022-10-31 07:54 UTC, Kok-je approved these changes
LGBT

2022-10-31 07:54 UTC, chao890 approved these changes

2022-10-31 08:15 UTC, merged