Add PPP prittam
AY2223S1-CS2103T-T15-1/tp pull request #241
Opened 2022-11-01 19:08 UTC by prit3010

Updated Add PPP Prittam

2022-11-02 04:26 UTC, Kok-je requested changes
Overall LGTM, detailed PPP other than some minor phrasing/ grammar errors

2022-11-02 04:26 UTC, Kok-je commented on docs/team/prit3010.md
> +    * Use Case: User can add multiple employees at once if the user has them inputted in a `.csv` file
abit of grammar issue here with the "if the user has them inputted ..." 

Consier "User can add multiple employees at once if they have the data in the form of a `.csv` file" or something to that extent.

2022-11-02 04:26 UTC, Kok-je commented on docs/team/prit3010.md
> +* Did heavy manual testing of the application to find for bugs
either "find bugs" or "look for bugs", slight grammar issue

2022-11-02 04:34 UTC, chao890 requested changes

2022-11-02 04:34 UTC, chao890 commented on docs/team/prit3010.md
> +    be stored in the `database.json`.
Can standardize punctuations here

2022-11-03 07:54 UTC, Kok-je approved these changes

2022-11-03 07:55 UTC, chao890 approved these changes

2022-11-03 08:05 UTC, merged