Update PPP
AY2223S1-CS2103T-T15-1/tp pull request #243
Opened 2022-11-02 04:19 UTC by chao890

Update PPP, almost complete now other than Developer guide contributions, which are still in progress.

2022-11-02 06:49 UTC, Kok-je requested changes
LGTM. Other than some minor phrasing errors. Can change it abit.

2022-11-02 06:49 UTC, Kok-je commented on docs/team/chao890.md
> +  * Refactor `Delete` command.
Past tense here: "Refactored"

2022-11-02 06:49 UTC, Kok-je commented on docs/team/chao890.md
> +  * Improved on the `Leave` class, by storing `Leave` objects in a priority queue, and adding methods to check for overlapping or equal leaves.
Consider rephrasing: "Made improvements to `Leave` class by storing..." , "implemented methods to..."

also remove comma after class and queue.

2022-11-03 07:52 UTC, kevinchangjk approved these changes
LGTM.

2022-11-03 07:53 UTC, Kok-je approved these changes

2022-11-03 08:04 UTC, merged