Feature batch add function
AY2223S1-CS2103T-T15-1/tp pull request #91
Opened 2022-10-16 11:53 UTC by prit3010

Fixes #79 

Added Batch Add Functionality where the User can add a group of people at once instead of adding them one by one.

Brief Overview on the feature:
- CSV File containing all the information is stored in `data` folder
- Type the Command Prompt with the filename into the system
- `BatchAddParser` will parse for the filename
- `getInfo()` reads the csv file and returns a `List<AddCommand>`
- When `execute` is run, will execute all the AddCommands in the List

Additional Features:
- If duplicates are found in the list of the CSV, the whole function will be aborted

Test Cases:
- Test Cases are still limited
- Unsure on how to create Test case for success

2022-10-16 13:17 UTC, kevinchangjk requested changes
There's a couple things that needs changing.

![image](https://user-images.githubusercontent.com/78629832/196037429-077db56a-a1f8-413a-859a-c2080bd1f0d1.png)

Here, I ran `batchadd BatchAddSuccess.csv` once, deleted the two new entries, then ran it again. The numbers are a bit funny cause I did more stuff before this sequence, but the point here is that the `EmployeeId` fields are not reverted when a batch add command fails.

Might have to call the `EmployeeId::setCount` method after failing, to reset it to before the command.

Additionally, you can see the other comments I left:
- some minor coding changes/suggestions
- extra blank lines
- `System.out.println` left behind

2022-10-16 13:17 UTC, kevinchangjk commented on src/main/java/coydir/logic/commands/BatchAddCommand.java
> +            e.printStackTrace();
Applies for line 77 below also.

Can we not print the error stack? It kinda ruins the logging in the terminal.

![image](https://user-images.githubusercontent.com/78629832/196036959-e89d244c-1e6d-4a93-b7ff-7a6eef5e9ed0.png)

2022-10-17 14:53 UTC, prit3010 commented on src/main/java/coydir/logic/parser/AddCommandParser.java
> +        System.out.println(args);
Resolved

2022-10-17 14:53 UTC, prit3010 commented on src/main/java/coydir/logic/parser/ParserUtil.java
> +
Resolved

2022-10-17 14:54 UTC, prit3010 commented on src/main/java/coydir/model/ModelManager.java
> +
Resolved

2022-10-17 14:54 UTC, prit3010 commented on src/main/java/coydir/model/ModelManager.java
> +
Resolved

2022-10-17 14:54 UTC, prit3010 commented on src/test/java/coydir/logic/commands/AddCommandTest.java
> +        System.out.println(modelStub.personsAdded.get(0).toString());
Resolved

2022-10-17 14:54 UTC, prit3010 commented on src/test/java/coydir/logic/commands/AddCommandTest.java
> +
Resolved

2022-10-17 14:54 UTC, prit3010 commented on src/test/java/coydir/testutil/TypicalPersons.java
> +
Resolved

2022-10-17 14:54 UTC, prit3010 commented on src/main/java/coydir/logic/parser/BatchAddCommandParser.java
> +
Resolved

2022-10-17 14:56 UTC, prit3010 commented on src/main/java/coydir/logic/commands/BatchAddCommand.java
> +            Database ab = new Database();
`model.getDatabase()` returns a `ReadOnlyDatabase` which does not have the `setPersons` method. So I have to instantiate a new `Database` to write into it

2022-10-17 14:56 UTC, prit3010 commented on src/main/java/coydir/logic/commands/BatchAddCommand.java
> +        if (addCommandList.isEmpty()) {
Resolved

2022-10-17 14:57 UTC, prit3010 commented on src/main/java/coydir/logic/commands/AddCommand.java
> +    public static final String MESSAGE_DUPLICATE_PERSON = "%1$s already exists in the address book";
Resolved

2022-10-18 03:43 UTC, kevinchangjk approved these changes

2022-10-18 03:44 UTC, merged